### PR TITLE
Update with signed dependencies

### PR DESCRIPTION
**Pull request by christophe-zurn-sonarsource**
Note updating either commons-io or guava makes the build fail, so we leave them as is for now

### CODE REVIEW

**Review by pynicolas — APPROVED** [review]
I think we could also update commons-io and guava.

**Comment by christophe-zurn-sonarsource** [comment]
@pynicolas I've updated commons-io and junit to latest version, but guava dependency is too old, if I update to latest version, I get build issues with the jarjar goal. Given that these updates are "nice to have", I'd leave the current guava version for now. WDYT ?

**Comment by pynicolas** [comment]
> @pynicolas I've updated commons-io and junit to latest version, but guava dependency is too old, if I update to latest version, I get build issues with the jarjar goal. Given that these updates are "nice to have", I'd leave the current guava version for now. WDYT ?

Ok for me if we create a ticket to later update this dependency or drop it.

**Comment by christophe-zurn-sonarsource** [comment]
@pynicolas Yep, there's already SONARFLEX-166, to remove Guava

**Pull request merged**
